In [1]:
from sklearn.preprocessing import StandardScaler
import joblib
import pandas as pd

In [2]:
ID_COLUMN = "comment_id"
TEXT_COLUMN = "comment_text"
DATASET_PATH = "https://ytcommentstorage.blob.core.windows.net/transformed-data/llm_cleaned.parquet?sv=2026-02-06&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2026-07-17T22:04:00Z&st=2026-06-17T13:49:00Z&spr=https&sig=kiL%2BVdjsVrc0PRmMNVAmLuG%2BpYEqTJpC%2BufjbP8dJU4%3D"

df = pd.read_parquet(DATASET_PATH)

emotion_columns = [
    col for col in df.columns
    if col not in [ID_COLUMN, TEXT_COLUMN]
]

X = df[emotion_columns]

print(X.shape)

(61079, 28)

In [3]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=emotion_columns,
    index=df.index
)

X_scaled.head()

,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,-0.468964,0.054959,4.238163,7.972156,-0.562920,-0.473405,-0.220090,-0.266303,-0.255730,0.999003,...,-0.303048,-0.307088,-0.396475,-0.200539,-0.337736,-0.396863,-0.198793,-0.450829,-0.055406,-0.541746
1,-0.451183,-0.106158,0.226987,0.246696,-0.543016,-0.446506,-0.190537,-0.233795,4.504787,0.147599,...,-0.270368,-0.046303,0.520207,-0.155581,-0.384399,-0.402691,-0.209150,-0.286621,-0.054151,-0.554262
2,-0.450968,-0.140866,-0.066077,0.468519,0.564387,1.479282,-0.234139,-0.261821,-0.199867,-0.493969,...,-0.299947,-0.300440,0.700209,-0.100990,-0.365538,0.038257,-0.222914,-0.527694,-0.173185,-0.145300
3,-0.459893,-0.146448,-0.050691,0.360819,-0.371426,-0.419434,-0.225197,-0.258718,-0.243636,-0.401305,...,-0.299857,0.371526,-0.358743,-0.170014,-0.354973,-0.257851,-0.262838,-0.460840,-0.154983,-0.429491
4,-0.476383,-0.124842,-0.183468,-0.290332,-0.529544,-0.455667,0.930189,2.376182,-0.253125,-0.459289,...,-0.297100,1.171948,-0.397261,-0.224187,0.076538,-0.311327,-0.219073,-0.497806,0.462019,-0.397170

In [4]:
scaled_summary = pd.DataFrame({
    "Mean": X_scaled.mean(),
    "Std Dev": X_scaled.std()
})

scaled_summary

                        Mean   Std Dev
admiration     -2.978093e-17  1.000008
amusement       6.979905e-18  1.000008
anger           3.722616e-18  1.000008
annoyance      -6.281915e-18  1.000008
approval       -3.722616e-18  1.000008
caring          0.000000e+00  1.000008
confusion      -1.116785e-17  1.000008
curiosity      -1.861308e-17  1.000008
desire         -1.489046e-17  1.000008
disappointment  7.445232e-18  1.000008
disapproval    -1.023719e-17  1.000008
disgust         7.445232e-18  1.000008
embarrassment  -3.722616e-18  1.000008
excitement      1.489046e-17  1.000008
fear            2.978093e-17  1.000008
gratitude      -1.489046e-17  1.000008
grief           5.956186e-17  1.000008
joy            -7.445232e-18  1.000008
love            7.445232e-18  1.000008
nervousness     1.489046e-17  1.000008
optimism        0.000000e+00  1.000008
pride          -3.722616e-18  1.000008
realization     2.233570e-17  1.000008
relief          2.419701e-17  1.000008
remorse         1.861308e-17  1.000008
sadness        -1.489046e-17  1.000008
surprise       -1.116785e-17  1.000008
neutral         1.489046e-17  1.000008

In [5]:
print("Average Mean :", X_scaled.mean().mean())
print("Average Std  :", X_scaled.std().mean())

Average Mean : 2.9166033246380587e-18
Average Std  : 1.0000081862201358

In [6]:
joblib.dump(
    scaler,
    "standard_scaler.pkl"
)

['standard_scaler.pkl']

In [7]:
scaled_df = pd.concat(
    [
        df[[ID_COLUMN, TEXT_COLUMN]],
        X_scaled
    ],
    axis=1
)

scaled_df.to_parquet(
    "scaled_emotion_dataset.parquet",
    index=False
)

scaled_df.head()

,comment_id,comment_text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,UgzctbxqZgshZ8gon294AaABAg,This shit was retarded I wasn't even stressed ...,-0.468964,0.054959,4.238163,7.972156,-0.562920,-0.473405,-0.220090,-0.266303,...,-0.303048,-0.307088,-0.396475,-0.200539,-0.337736,-0.396863,-0.198793,-0.450829,-0.055406,-0.541746
1,Ugw-Y7stczH-a4Wv3T94AaABAg,Its terrible I wish it would just stop,-0.451183,-0.106158,0.226987,0.246696,-0.543016,-0.446506,-0.190537,-0.233795,...,-0.270368,-0.046303,0.520207,-0.155581,-0.384399,-0.402691,-0.209150,-0.286621,-0.054151,-0.554262
2,UgzWhdA-bcUlXL8n9_V4AaABAg,"Smell something gross it'll help calm you, hel...",-0.450968,-0.140866,-0.066077,0.468519,0.564387,1.479282,-0.234139,-0.261821,...,-0.299947,-0.300440,0.700209,-0.100990,-0.365538,0.038257,-0.222914,-0.527694,-0.173185,-0.145300
3,Ugz6ySN9lU9tN4rJutx4AaABAg,Just came here for a bit of reassurance after ...,-0.459893,-0.146448,-0.050691,0.360819,-0.371426,-0.419434,-0.225197,-0.258718,...,-0.299857,0.371526,-0.358743,-0.170014,-0.354973,-0.257851,-0.262838,-0.460840,-0.154983,-0.429491
4,UgwSP4dqy6_mJmFJ6Wd4AaABAg,Ohh so you're telling me i have been having pa...,-0.476383,-0.124842,-0.183468,-0.290332,-0.529544,-0.455667,0.930189,2.376182,...,-0.297100,1.171948,-0.397261,-0.224187,0.076538,-0.311327,-0.219073,-0.497806,0.462019,-0.397170