In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('./data.parquet')

In [3]:
df.head()

,comment_id,video_id,author,comment_text,likes,published_at,keep
0,UgwjNEdZkbl-Ql0Fi014AaABAg,16XD6zP_d8M,@PsychHub,Your voice matters! Submit anonymous feedback ...,18,2024-09-22T15:55:19Z,False
1,UgzctbxqZgshZ8gon294AaABAg,16XD6zP_d8M,@YoteThyself,This shit was retarded I wasn't even stressed ...,0,2026-06-22T19:26:17Z,True
2,Ugw-Y7stczH-a4Wv3T94AaABAg,16XD6zP_d8M,@Anisa-p7k,Its terrible I wish it would just stop,0,2026-06-19T17:30:47Z,True
3,UgzWhdA-bcUlXL8n9_V4AaABAg,16XD6zP_d8M,@jessicarodriguez3852,"Smell something gross it'll help calm you, hel...",0,2026-06-11T09:03:23Z,True
4,Ugye-dydTGZiMS290ax4AaABAg,16XD6zP_d8M,@Akramk48,i am always scared when i am trying to go to s...,0,2026-05-31T20:46:01Z,False

In [4]:
df.tail()

,comment_id,video_id,author,comment_text,likes,published_at,keep
22047,Ugh0BhGUrAD1ZHgCoAEC,v-t1Z5-oPtU,@Blopdy,who is this voice actor?,0,2015-10-22T15:21:20Z,True
22048,UggaKYhwx3UD5XgCoAEC,v-t1Z5-oPtU,@actionbeambbbbbbb,the animation and sfx are awesome,401,2015-10-22T15:19:30Z,False
22049,UghS0P6WxuIJdHgCoAEC,v-t1Z5-oPtU,@johneydermon1,A full health bar in a game starts at 10%? 0:39,4,2015-10-22T15:15:38Z,True
22050,UgiBCFvFYLVhQngCoAEC,v-t1Z5-oPtU,@jigarsoni,can anyone tell me how to make animated videos...,4,2015-10-22T15:15:35Z,True
22051,UgiMrVLNy76ZIXgCoAEC,v-t1Z5-oPtU,@irun_mon,Too early to comment. lel,0,2015-10-22T15:11:23Z,False

In [6]:
df.shape

(22052, 7)

In [7]:
df.columns

Index(['comment_id', 'video_id', 'author', 'comment_text', 'likes',
       'published_at', 'keep'],
      dtype='str')

In [8]:
df.dtypes

comment_id         str
video_id           str
author             str
comment_text       str
likes            int64
published_at       str
keep            object
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22052 entries, 0 to 22051
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   comment_id    22052 non-null  str
 1   video_id      22052 non-null  str
 2   author        22052 non-null  str
 3   comment_text  22052 non-null  str
 4   likes         22052 non-null  int64
 5   published_at  22052 non-null  str
 6   keep          19235 non-null  object
dtypes: int64(1), object(1), str(5)
memory usage: 7.7+ MB

In [10]:
df.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(8.279719352722168)

In [11]:
df.select_dtypes(include="number").columns.tolist()

['likes']

In [12]:
df.select_dtypes(exclude="number").columns.tolist()

['comment_id', 'video_id', 'author', 'comment_text', 'published_at', 'keep']