In [1]:
import pandas as pd

In [2]:
path = "https://ytcommentstorage.blob.core.windows.net/transformed-data/llm_cleaned.parquet?sv=2026-02-06&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2026-07-17T22:04:00Z&st=2026-06-17T13:49:00Z&spr=https&sig=kiL%2BVdjsVrc0PRmMNVAmLuG%2BpYEqTJpC%2BufjbP8dJU4%3D"
df = pd.read_parquet(path)

In [3]:
df.head()

,comment_id,comment_text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,UgzctbxqZgshZ8gon294AaABAg,This shit was retarded I wasn't even stressed ...,0.003028,0.020176,0.247202,0.688535,0.002181,0.001121,0.001745,0.001045,...,0.000603,0.002827,0.003117,0.001313,0.015120,0.001427,0.004839,0.024739,0.008314,0.007993
1,Ugw-Y7stczH-a4Wv3T94AaABAg,Its terrible I wish it would just stop,0.008128,0.005138,0.024323,0.052187,0.005455,0.007038,0.003924,0.004886,...,0.006559,0.039559,0.153237,0.002270,0.009849,0.001231,0.004243,0.067893,0.008400,0.005041
2,UgzWhdA-bcUlXL8n9_V4AaABAg,"Smell something gross it'll help calm you, hel...",0.008189,0.001899,0.008039,0.070458,0.187611,0.430680,0.000710,0.001575,...,0.001168,0.003764,0.182715,0.003432,0.011980,0.016038,0.003452,0.004539,0.000233,0.101517
3,Ugz6ySN9lU9tN4rJutx4AaABAg,Just came here for a bit of reassurance after ...,0.005630,0.001378,0.008894,0.061587,0.033680,0.012994,0.001369,0.001941,...,0.001185,0.098410,0.009296,0.001963,0.013173,0.006095,0.001154,0.022108,0.001482,0.034475
4,UgwSP4dqy6_mJmFJ6Wd4AaABAg,Ohh so you're telling me i have been having pa...,0.000900,0.003395,0.001516,0.007951,0.007671,0.005023,0.086526,0.313221,...,0.001687,0.211149,0.002988,0.000810,0.061911,0.004299,0.003673,0.012394,0.043815,0.042100

In [4]:
df.tail()

,comment_id,comment_text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
61074,Ugy3uRGgEvrt8nbWqGF4AaABAg,Thank you very much!,0.005137,0.001275,0.000674,0.001097,0.002713,0.000456,0.000645,0.000739,...,0.001054,0.000123,0.001111,0.000210,0.001988,0.000752,0.000304,0.000736,0.000468,0.001614
61075,Ugxhs7BtZoP_QrGaPXl4AaABAg,The amount of dislikes on this is godly,0.015761,0.000312,0.005941,0.057569,0.052904,0.001824,0.001098,0.000576,...,0.001625,0.000900,0.002226,0.001241,0.018449,0.000966,0.000432,0.005279,0.000877,0.405312
61076,UgzFTJgvJw4mb1K0VTp4AaABAg,I immediately pressed after seeing this,0.001575,0.002211,0.000577,0.004164,0.054601,0.000420,0.000304,0.000453,...,0.000309,0.000285,0.002935,0.000342,0.028853,0.000342,0.000118,0.000562,0.000809,0.950148
61077,UgwcHjp3nkjFgT8iXxl4AaABAg,I cannot believe this precious video is underr...,0.815267,0.001798,0.009053,0.040957,0.044069,0.002174,0.010081,0.007478,...,0.030874,0.001107,0.002978,0.036983,0.028012,0.007991,0.002480,0.008509,0.214234,0.018084
61078,UgxonOAJWVj5nIXw5y14AaABAg,Thank you very much 💕,0.005618,0.001545,0.001107,0.001635,0.002769,0.000551,0.000582,0.000681,...,0.001869,0.000127,0.000942,0.000237,0.001902,0.000965,0.000364,0.000896,0.000446,0.001299

In [5]:
df.shape

(61079, 30)

In [6]:
df.columns

Index(['comment_id', 'comment_text', 'admiration', 'amusement', 'anger',
       'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire',
       'disappointment', 'disapproval', 'disgust', 'embarrassment',
       'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love',
       'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse',
       'sadness', 'surprise', 'neutral'],
      dtype='str')

In [7]:
df.dtypes

comment_id            str
comment_text          str
admiration        float64
amusement         float64
anger             float64
annoyance         float64
approval          float64
caring            float64
confusion         float64
curiosity         float64
desire            float64
disappointment    float64
disapproval       float64
disgust           float64
embarrassment     float64
excitement        float64
fear              float64
gratitude         float64
grief             float64
joy               float64
love              float64
nervousness       float64
optimism          float64
pride             float64
realization       float64
relief            float64
remorse           float64
sadness           float64
surprise          float64
neutral           float64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61079 entries, 0 to 61078
Data columns (total 30 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   comment_id      61079 non-null  str
 1   comment_text    61079 non-null  str
 2   admiration      61079 non-null  float64
 3   amusement       61079 non-null  float64
 4   anger           61079 non-null  float64
 5   annoyance       61079 non-null  float64
 6   approval        61079 non-null  float64
 7   caring          61079 non-null  float64
 8   confusion       61079 non-null  float64
 9   curiosity       61079 non-null  float64
 10  desire          61079 non-null  float64
 11  disappointment  61079 non-null  float64
 12  disapproval     61079 non-null  float64
 13  disgust         61079 non-null  float64
 14  embarrassment   61079 non-null  float64
 15  excitement      61079 non-null  float64
 16  fear            61079 non-null  float64
 17  gratitude       61079 non-null  float64
 18  grief           61079 non-null  float64
 19  joy             61079 non-null  float64
 20  love            61079 non-null  float64
 21  nervousness     61079 non-null  float64
 22  optimism        61079 non-null  float64
 23  pride           61079 non-null  float64
 24  realization     61079 non-null  float64
 25  relief          61079 non-null  float64
 26  remorse         61079 non-null  float64
 27  sadness         61079 non-null  float64
 28  surprise        61079 non-null  float64
 29  neutral         61079 non-null  float64
dtypes: float64(28), str(2)
memory usage: 30.5 MB

In [9]:
df.memory_usage(deep=True).sum() / (1024 ** 2)

np.float64(30.54841423034668)

In [10]:
df.select_dtypes(include="number").columns.tolist()

['admiration',
 'amusement',
 'anger',
 'annoyance',
 'approval',
 'caring',
 'confusion',
 'curiosity',
 'desire',
 'disappointment',
 'disapproval',
 'disgust',
 'embarrassment',
 'excitement',
 'fear',
 'gratitude',
 'grief',
 'joy',
 'love',
 'nervousness',
 'optimism',
 'pride',
 'realization',
 'relief',
 'remorse',
 'sadness',
 'surprise',
 'neutral']

In [11]:
df.select_dtypes(exclude="number").columns.tolist()

['comment_id', 'comment_text']